# docker build --platform linux/amd64 -t l241025097/python:3.8.0 -f Dockerfile.base .
FROM dockerpull.cn/python:3.8
RUN apt-get clean && apt-get install -y apt-transport-https
RUN apt-get update && apt-get install -y git
RUN apt-get install -y wget
RUN apt-get install -y vim
RUN apt-get install -y iputils-ping
RUN apt-get install -y telnet
RUN apt-get install -y traceroute
RUN apt-get install -y libterm-readkey-perl
RUN apt-get install -y locales
RUN apt-get install -y locales-all
RUN locale-gen en_US.UTF-8
RUN echo ":set mouse-=a" > ~/.vimrc
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata
RUN apt-get install cron rsyslog -y
RUN mkdir -p /home/jd
RUN python -m pip install --upgrade pip
RUN pip install ddddocr==1.4.7 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install gate-api==4.70.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install greenlet==3.1.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install lxml==4.9.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install cssselect==1.2.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install matplotlib==3.7.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install numpy==1.24.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pandas==2.0.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install requests==2.31.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install paramiko==2.8.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pillow==9.4.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install selenium==4.11.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install scp -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install sqlalchemy==2.0.21 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pyarrow==16.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install ipython==7.33.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install xlsxwriter==3.0.3 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install xlrd==2.0.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install flask==2.0.0 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install Werkzeug==2.2.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install gevent==24.11.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install pymysql==1.0.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
